gentoo/qt

lxqt-base/liblxqt-mount/liblxqt-mount-9999.ebuild
lxqt-base/liblxqt/liblxqt-9999.ebuild
lxqt-base/libsysstat/libsysstat-9999.ebuild
lxqt-base/lxqt-about/lxqt-about-9999.ebuild
lxqt-base/lxqt-common/lxqt-common-9999.ebuild
lxqt-base/lxqt-config-randr/lxqt-config-randr-9999.ebuild
lxqt-base/lxqt-config/lxqt-config-9999.ebuild
lxqt-base/lxqt-globalkeys/lxqt-globalkeys-9999.ebuild
lxqt-base/lxqt-notificationd/lxqt-notificationd-9999.ebuild
lxqt-base/lxqt-panel/lxqt-panel-9999.ebuild
lxqt-base/lxqt-policykit/lxqt-policykit-9999.ebuild
lxqt-base/lxqt-powermanagement/lxqt-powermanagement-9999.ebuild
lxqt-base/lxqt-qtplugin/lxqt-qtplugin-9999.ebuild
lxqt-base/lxqt-runner/lxqt-runner-9999.ebuild
lxqt-base/lxqt-session/lxqt-session-9999.ebuild

On 18.01.2015 J. Leclanche announced on the LXDE mailing list that the
package download path will change in a few weeks (with the release of
0.9.0). The change of download paths affacts all version.
The new locations are already working, so here is the change that needs
to be done.

[lxqt-base] LXQt SRC_URI change

---

dev-qt/qtwebkit23/files/qtwebkit23-2.3.4-use-correct-typedef.patch
dev-qt/qtwebkit23/qtwebkit23-2.3.4.ebuild

Add a patch to let it build when libxml2 is compiled with icu support
enabled. This solves conflicts with, e.g., chromium depending on
libxml2[icu]
I tested this ebuild to see if it is solving bug #522880 (when phonon-gstreamer-4.8.x is used there is a gstreamer 0.10, loaded by qtwebkit, vs 1.x, loaded by phonon, symbol collision in applications needing both gstreamer and qtwebkit, like amarok). The issue is solved as expected and phonon-gstreamer 4.8 works as expected. See also comment #35 in bug #522880
Note this ebuild currently generates a file collision with dev-qt/qtdeclarative-4.8.x
```
* Detected file collision(s):
*
*      /usr/lib64/qt4/imports/QtWebKit/libqmlwebkitplugin.so
*      /usr/lib64/qt4/imports/QtWebKit/qmldir
*
* Searching all installed packages for file collisions... …
```

[dev-qt/qtwebkit23] add support for building with libxml2[icu]

---

sets/lxqt-live

lxqt-openssh-askpass-9999 moved from net-misc/ to lxqt-base/
Signed-off-by: Ioan-Adrian Ratiu <adi@adirat.com>

sets/lxqt-live: update lxqt-openssh-askpass location

---

dev-qt/qtwebengine/files/qtwebengine-5.6.0-nss-3.23-01.patch
dev-qt/qtwebengine/files/qtwebengine-5.6.0-nss-3.23-02.patch
dev-qt/qtwebengine/qtwebengine-5.6.0.ebuild

dev-qt/qtwebengine: Fix 5.6.0 build with system-nss

---

dev-qt/qtdbus/qtdbus-5.8.9999.ebuild
dev-qt/qtdbus/qtdbus-5.9999.ebuild

For the live-builds, the files we want to remove will be under the build directory, not the source directory.  Without this change, the files are not found.
For at least 5.8.0, it seems like it might be enough to have the 'src/corelib' added to 'QT5_TARGET_SUBDIRS'.  I'm not super sure of that yet, so I may be missing something more or/and less obvious.

dev-qt/qtdbus: Adjust the awful hack to make 'qtdbus' build.

---

dev-qt/qtcore/files/qtcore-5.11.0-restore-qt5_use_modules.patch
dev-qt/qtcore/qtcore-5.11.0.ebuild

This is certainly better than spending even more energy on fixing upstreams.
See also: https://codereview.qt-project.org/#/c/232367/
Bug: https://bugs.gentoo.org/653646
Package-Manager: Portage-2.3.40, Repoman-2.3.9

dev-qt/qtcore: Restore qt5_use_modules macro

---

eclass/qmake-utils.eclass

Last consumer in Gentoo ebuild repository was dropped.

qmake-utils.eclass: Drop obsolete EAPI-5 support

---

eclass/qt5-build.eclass

Closes: https://bugs.gentoo.org/699248

qt5-build.eclass: Disable zstd for Qt5 >=5.13.2 RCC compression

---

dev-qt/qtgui/qtgui-5.14.9999.ebuild
dev-qt/qtgui/qtgui-5.15.9999.ebuild
dev-qt/qtgui/qtgui-5.9999.ebuild

Closes: https://bugs.gentoo.org/707658
Package-Manager: Portage-2.3.87, Repoman-2.3.20

dev-qt/qtgui: More fine-grained subslot

---

dev-qt/qtwayland/qtwayland-5.14.9999.ebuild
dev-qt/qtwayland/qtwayland-5.15.9999.ebuild
dev-qt/qtwayland/qtwayland-5.9999.ebuild

So the first results are in wrt fixing the dev-qt/qtwayland[X] automagic by using the appropriate build switches: https://bugs.gentoo.org/713362
Please note that I think the dependency is suboptimal, even if necessary.
This affects users who globally enable gles2 for whatever reasons and don't use desktop profile for whatever reasons, where this is masked for Qt packages.
The best way to tackle this imo is to finally rename the gles2 flag, see also: https://archives.gentoo.org/gentoo-dev/message/ab302ac2ab641b1e82acad7d32308266
For `gles2-only` there is already usage found in net-libs/webkit-gtk and x11-libs/cairo.

dev-qt/qtwayland: USE X requires !dev-qt/qtgui[gles2]

---

dev-qt/qdoc/qdoc-5.14.9999.ebuild
eclass/qt5-build.eclass

Fixed upstream in 5.11.1.
See also: https://bugreports.qt.io/browse/QTBUG-37417
Upstream commit 67aa365d41ebfe082b4efcfd725e4d5f08be678c
Bug: https://bugs.gentoo.org/497312
Bug: https://bugs.gentoo.org/676948
I think at least dev-qt/qdoc will need to be adapted as well for that change.

qt5-build.eclass: Drop obsolete in-source build workaround for >=5.14.2

---

dev-qt/qtcore/metadata.xml
dev-qt/qtcore/qtcore-5.15.0_beta3.ebuild
dev-qt/qtcore/qtcore-5.15.9999.ebuild
dev-qt/qtcore/qtcore-5.9999.ebuild

Now that we have this flag, we could use it to make >=5.15 a bit edgier.
Bug: https://bugs.gentoo.org/672856

dev-qt/qtcore: In >=5.15, disable statx only with IUSE="old-kernel"

---

dev-qt/qtdeclarative/qtdeclarative-5.15.9999.ebuild

Closes: https://bugs.gentoo.org/733674
5.14.2 and 5.15.0 in tree should receive revbumps for the same change, I guess.

dev-qt/qtdeclarative: Trigger rebuild on dev-qt/qtgui subslot update

---

dev-qt/qtbluetooth/qtbluetooth-5.15.9999.ebuild

Uses private QtCore headers.
Package-Manager: Portage-3.0.1, Repoman-2.3.23

dev-qt/qtbluetooth: Trigger rebuild on dev-qt/qtcore subslot update

---

dev-qt/assistant/assistant-5.15.9999.ebuild
dev-qt/designer/designer-5.15.9999.ebuild
dev-qt/designer/metadata.xml

[qtwebkit-removal](https://bugs.gentoo.org/show_bug.cgi?id=qtwebkit-removal) is progressing well and it is probably time to remove any ties from `dev-qt` category.

dev-qt: Drop IUSE=webkit

---

dev-qt/qtwayland/qtwayland-5.15.9999.ebuild

Package is using private headers from qtcore, qtdeclarative, qtgui.

dev-qt/qtwayland: Add missing slot ops

---

dev-qt/qtchooser/qtchooser-9999.ebuild
eclass/qt5-build.eclass

- sync with gentoo.git dropping `dev-qt/qtchooser` from default `RDEPEND` but stop short of picking https://github.com/gentoo/gentoo/commit/072da15f03fea298ef12bfec3ea8ac95f85a15d5 (not necessary imo and so qt overlay users may test w/o Qt binaries in `PATH`)
- plus move qtchooser config from eclass to qtchooser ebuild, both picked from https://github.com/gentoo/gentoo/pull/18810

qt5-build.eclass cleanup

---

dev-qt/qtwebengine/qtwebengine-5.15.9999.ebuild
eclass/qt5-build.eclass

What do we think about this?
Should we wait and see for a while longer, or go ahead and make use of it?

Use KDE upstream for 5.15 live builds.

---

eclass/qt5-build.eclass

Necessary `kde.org.eclass` changes were already pushed to Gentoo ebuild repository.

Support kde.org.eclass snapshots and use it for live repository handling; fix eclassdoc

---

dev-qt/qtwidgets/qtwidgets-5.15.2.9999.ebuild

New use flag builds Qt5 plugin for integration with flatpak and snap.
Add missing IUSE=gtk dependencies. No additional dependencies with
IUSE=dbus means the added REQUIRED_USE is cheap, and sys-apps/dbus is
already pulled in by x11-libs/gtk+3 (via dev-libs/glib) unconditionally.

dev-qt/qtwidgets: Add IUSE=dbus to enable xdgdesktopportal build

---

dev-qt/qtwebengine/qtwebengine-5.15.2.9999.ebuild

This is not yet very comprehensively looked into, basically the result of `emerge -Cv libglvnd` output:
```
- /usr/lib64/libEGL.so.1
- /usr/lib64/libEGL.so.1.1.0
.../qt5/plugins/platforms/libqwayland-egl.so (dev-qt/qtwayland-5.15.2-r11)
.../qt5/plugins/platforms/libqwayland-xcomposite-egl.so (dev-qt/qtwayland-5.15.2-r11)
.../qt5/plugins/wayland-graphics-integration-client/libdmabuf-server.so (dev-qt/qtwayland-5.15.2-r11)
.../qt5/plugins/wayland-graphics-integration-client/libdrm-egl-server.so (dev-qt/qtwayland-5.15.2-r11)
.../qt5/plugins/wayland-graphics-integration-client/libqt-plugin-wayland-egl.so (dev-qt/qtwayland-5.15.2-r11)
.../qt5/plugins/wayland-graphics-integration-client/libxcomposite-egl.so (dev-qt/qtwayland-5.15.2-r11) …
```

dev-qt: Switch GL/EGL impl to media-libs/libglvnd

---

dev-qt/qtwayland/qtwayland-5.15.3.9999.ebuild
dev-qt/qtwaylandscanner/metadata.xml
dev-qt/qtwaylandscanner/qtwaylandscanner-5.15.3.9999.ebuild

Sort of a messy split, but I did not quite know how else to do it.
Ideally we would be able to split off the compositor but that is rather tricky.

dev-qt/qtwaylandscanner split

---

dev-qt/qtdeclarative/qtdeclarative-5.15.5.9999.ebuild

Bug: https://bugs.gentoo.org/840861
Package-Manager: Portage-3.0.30, Repoman-3.0.3

dev-qt/qtdeclarative: Filter -Os

---

dev-qt/qtnetwork/metadata.xml
dev-qt/qtnetwork/qtnetwork-5.15.10.9999.ebuild

Upstream in #kde-devel:
- the bearer plugins were created in another era: for Symbian, when we weren't always connected to the Internet and the user maybe didn't want to turn on their data
- now, we're always connected, so the bearer plugins are unnecessary
- they've been removed from Qt 6 due to their design problems
- so just do the same in Qt 5: don't use them
- especially when upstream has already declared "the use of this API is a design flaw"
Can not drop src/plugins/bearer/generic (builds libqgenericbearer.so) though, as without it things like akonadi (KMail remains offline) and Plasma POTD stop working.
QTBUG: https://bugreports.qt.io/browse/QTBUG-114666

dev-qt/qtnetwork: Drop bearer plugins (IUSE=connman,networkmanager)

---

dev-qt/qtwayland/metadata.xml
dev-qt/qtwayland/qtwayland-5.15.11.9999.ebuild

Would have preferred a clean split but wayland-server depends on wayland-client in the buildsys.
- Drop IUSE vulkan: Merge with 'compositor' instead. This absolves us from having to make a default conflicting REQUIRED_USE with compositor.
- Drop IUSE X: Unused, broken upstream since 2021 and removed in Qt6. Quoting upstream from commit d4a7faff: "These plugins were created to allow testing/debugging of QtWayland- based compositors on desktops that did not support Wayland natively."
PS: Not runtime tested yet.

dev-qt/qtwayland: make compositor APIs off-by-default optional

---

eclass/qt5-build.eclass

Bug: https://bugs.gentoo.org/919789

qt5-build.eclass: filter-lto earlier for qtbase module packages

---

dev-qt/qtcore/qtcore-5.15.12.9999.ebuild

Revdeps can drop dev-qt/* dependencies on version bumps at any time, which then
may lead to Portage disregarding these dev-qt/* packages for upgrade if nothing
is left depending on them. When these packages contain Qt5 plugins it breaks
runtime hard - broken screenlocker, blank login manager, ... -, with:
`Cannot mix incompatible Qt library (5.15.10) with this library (5.15.11)`
We've had this happen with dev-qt/qtvirtualkeyboard and dev-qt/qtcharts already
and gradual porting to Qt6 ensures it will happen more often in the future.
For lack of a better mechanism from the package manager, this blocker package
makes sure dep calculation will take care of the necessary cleanup of dangling
Qt packages, even if it will not improve our backtracking situation.

dev-qt/qtcore - add wall of blockers against breakage
